# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ad251084c63322e3d3195fa255c80609"
name = "StickyCTA"
handle = "stickycta"
application_url = "https://cabin-carrying-institutions-diff.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "appsimo5.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://cabin-carrying-institutions-diff.trycloudflare.com/auth/callback",
  "https://cabin-carrying-institutions-diff.trycloudflare.com/auth/shopify/callback",
  "https://cabin-carrying-institutions-diff.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
